name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-24.04
    environment: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Build packages
        run: |
          pip install -r requirements/testing.txt
          make package
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error

  publish-to-pypi:
    name: Publish package on PyPI
    needs:
      - build
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.event.repository.name }}/${{ github.ref_name }}/
    permissions:
      id-token: write

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Publish package on GitHub Releases
    needs:
      - build
    runs-on: ubuntu-24.04
    environment:
      name: github-releases
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign packages
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --title "${GITHUB_REPOSITORY#*/} $GITHUB_REF_NAME"
      - name: Upload artifact signatures to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          "$GITHUB_REF_NAME" dist/**
          --repo "$GITHUB_REPOSITORY"
